# Generated by Django 6.0.6 on 2026-07-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_appointment_created_at_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports/'),
        ),
    ]
